apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-server-ci
  name: go-server-ci
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-server-ci
  template:
    metadata:
      labels:
        app: go-server-ci
    spec:
      containers:
      - image: docker pull ghcr.io/2023-4400-exp/4432-go-server-ci:3e9d8e2d970705b110ca5d286bdf1efe8c125255
        name: go-server-ci